apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-route
spec:
  hosts:
    - redis-service
  http:
    - route:
        - destination:
            host: redis-service
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx,connect-failure,refused-stream

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-policy
spec:
  host: redis-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
